USE [master]
GO

/****** Object:  Database [WeddingBuilder]    Script Date: 11/29/2015 11:33:35 AM ******/
CREATE DATABASE [WeddingBuilder]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'WeddingBuilder', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\WeddingBuilder.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'WeddingBuilder_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\WeddingBuilder_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [WeddingBuilder] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [WeddingBuilder].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [WeddingBuilder] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [WeddingBuilder] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [WeddingBuilder] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [WeddingBuilder] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [WeddingBuilder] SET ARITHABORT OFF 
GO

ALTER DATABASE [WeddingBuilder] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [WeddingBuilder] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [WeddingBuilder] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [WeddingBuilder] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [WeddingBuilder] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [WeddingBuilder] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [WeddingBuilder] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [WeddingBuilder] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [WeddingBuilder] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [WeddingBuilder] SET  DISABLE_BROKER 
GO

ALTER DATABASE [WeddingBuilder] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [WeddingBuilder] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [WeddingBuilder] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [WeddingBuilder] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [WeddingBuilder] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [WeddingBuilder] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [WeddingBuilder] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [WeddingBuilder] SET RECOVERY FULL 
GO

ALTER DATABASE [WeddingBuilder] SET  MULTI_USER 
GO

ALTER DATABASE [WeddingBuilder] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [WeddingBuilder] SET DB_CHAINING OFF 
GO

ALTER DATABASE [WeddingBuilder] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [WeddingBuilder] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [WeddingBuilder] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [WeddingBuilder] SET  READ_WRITE 
GO


