USE [WeddingSiteBuilder]
GO

/****** Object:  Table [dbo].[RSVPLink]    Script Date: 12/3/2015 10:09:29 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[RSVPLink](
	[RSVPLinkID] [bigint] IDENTITY(1,1) NOT NULL,
	[WeddingID] [bigint] NOT NULL,
	[PersonID] [bigint] NOT NULL,
	[RSVPNameBlub] [varchar](50) NOT NULL,
	[GuidToken] [uniqueidentifier] NOT NULL,
	[CreateDate] [datetime] NOT NULL,
	[LastUpdated] [datetime] NOT NULL,
 CONSTRAINT [PK_RSVPLink] PRIMARY KEY CLUSTERED 
(
	[RSVPLinkID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[RSVPLink]  WITH CHECK ADD  CONSTRAINT [FK_RSVPLink_Person] FOREIGN KEY([PersonID])
REFERENCES [dbo].[Person] ([PersonID])
GO

ALTER TABLE [dbo].[RSVPLink] CHECK CONSTRAINT [FK_RSVPLink_Person]
GO

ALTER TABLE [dbo].[RSVPLink]  WITH CHECK ADD  CONSTRAINT [FK_RSVPLink_Wedding] FOREIGN KEY([WeddingID])
REFERENCES [dbo].[Wedding] ([WeddingID])
GO

ALTER TABLE [dbo].[RSVPLink] CHECK CONSTRAINT [FK_RSVPLink_Wedding]
GO


